const C=window.TRIPSPLIT_CONFIG||{};
const root=document.getElementById('app'), toastEl=document.getElementById('toast');
let sb, session, currentTrip=null, members=[], expenses=[], deferredPrompt;
const qs=new URLSearchParams(location.search); const inviteToken=qs.get('invite');
const money=(n,c='INR')=>new Intl.NumberFormat('en-IN',{style:'currency',currency:c}).format(Number(n||0));
function toast(m,error=false){toastEl.textContent=m;toastEl.className='toast show'+(error?' error':'');setTimeout(()=>toastEl.className='toast',3200)}
function esc(s=''){return String(s).replace(/[&<>'"]/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[x]))}
function modal(title,body){document.body.insertAdjacentHTML('beforeend',`<div class="modal-wrap" id="modalWrap"><div class="modal"><div class="modal-head"><h2>${esc(title)}</h2><button class="icon-btn" onclick="closeModal()">✕</button></div>${body}</div></div>`)}
function closeModal(){document.getElementById('modalWrap')?.remove()}
window.closeModal=closeModal;
async function init(){
 if(!C.SUPABASE_URL||C.SUPABASE_URL.includes('YOUR-')||!C.SUPABASE_ANON_KEY||C.SUPABASE_ANON_KEY.includes('YOUR_')) return setupScreen();
 sb=supabase.createClient(C.SUPABASE_URL,C.SUPABASE_ANON_KEY,{auth:{persistSession:true,autoRefreshToken:true}});
 const {data}=await sb.auth.getSession(); session=data.session;
 if(!session){const {data:d,error}=await sb.auth.signInAnonymously();if(error)return fatal('Anonymous sign-in failed: '+error.message+'. Enable Anonymous Sign-Ins in Supabase Authentication settings.');session=d.session}
 if(inviteToken) return joinScreen();
 await home();
}
function setupScreen(){root.innerHTML=`<section class="card"><span class="eyebrow">One-time setup</span><h1>Connect Supabase</h1><p class="muted">Copy <b>config.example.js</b> to <b>config.js</b>, add your project URL and anon key, then deploy again.</p><div class="warning">Never place a service-role key in this browser app. Use only the public anon key.</div></section>`}
function fatal(m){root.innerHTML=`<section class="card"><h2>Cannot start</h2><p class="warning">${esc(m)}</p></section>`}
async function home(){
 const {data,error}=await sb.rpc('my_trips'); if(error)return fatal(error.message);
 root.innerHTML=`<section class="hero"><div class="card hero-main"><span class="eyebrow">Private by design</span><h1>Split the trip.<br>Not the friendship.</h1><p>Create a trip, add invitation slots, and let each traveler join by scanning a one-time QR code. End Trip exports the workbook and permanently removes the trip data.</p><div class="actions"><button class="btn" onclick="createTripModal()">Create trip</button></div></div><div class="card"><h2>Your trips</h2><div class="list">${data?.length?data.map(t=>`<button class="row" onclick="openTrip('${t.trip_id}')"><span class="row-main"><strong>${esc(t.name)}</strong><span class="muted">${esc(t.destination||'No destination')}</span></span><span class="pill ${t.role==='ADMIN'?'admin':''}">${t.role}</span></button>`).join(''):'<div class="empty">No trips yet. Create your first trip.</div>'}</div></div></section>`;
}
function createTripModal(){modal('Create trip',`<form id="createTripForm" class="form-grid"><div class="field full"><label>Trip name</label><input name="name" maxlength="80" required placeholder="Goa Weekend"></div><div class="field"><label>Destination</label><input name="destination" maxlength="100" placeholder="Goa"></div><div class="field"><label>Currency</label><select name="currency"><option>INR</option><option>USD</option><option>EUR</option><option>GBP</option><option>AED</option><option>SGD</option></select></div><div class="field"><label>Start date</label><input type="date" name="start_date"></div><div class="field"><label>End date</label><input type="date" name="end_date"></div><div class="field full"><label>Your display name</label><input name="display_name" maxlength="60" required value="Admin"></div><div class="field full"><button class="btn">Create trip</button></div></form>`);document.getElementById('createTripForm').onsubmit=async e=>{e.preventDefault();let p=Object.fromEntries(new FormData(e.target));let {data,error}=await sb.rpc('create_trip',p);if(error)return toast(error.message,true);closeModal();await openTrip(data)}}
async function openTrip(id){
 const {data,error}=await sb.rpc('trip_dashboard',{p_trip_id:id}); if(error)return toast(error.message,true);
 currentTrip=data.trip;members=data.members||[];expenses=data.expenses||[];
 renderTrip();
}
function renderTrip(){
 const admin=currentTrip.role==='ADMIN', total=expenses.reduce((s,e)=>s+Number(e.amount),0), myId=currentTrip.member_id;
 const balances=calcBalances();
 root.innerHTML=`<div class="actions"><button class="btn secondary" onclick="home()">← All trips</button></div><section class="grid"><div class="card col-8"><span class="eyebrow">${esc(currentTrip.destination||'Trip')}</span><h1>${esc(currentTrip.name)}</h1><p class="muted">${currentTrip.started_at?'Trip started':'Planning'} · ${esc(currentTrip.currency)}</p><div class="stats"><div class="stat"><strong>${money(total,currentTrip.currency)}</strong><small>Total expenses</small></div><div class="stat"><strong>${members.length}</strong><small>Travelers</small></div><div class="stat"><strong>${expenses.length}</strong><small>Entries</small></div></div><div class="actions">${admin&&!currentTrip.started_at?'<button class="btn success" onclick="startTrip()">Start trip</button>':''}${currentTrip.started_at?'<button class="btn" onclick="expenseModal()">Add expense</button>':''}${admin?'<button class="btn secondary" onclick="inviteModal()">Add user / QR</button><button class="btn danger" onclick="endTrip()">End trip & export</button>':''}</div></div><div class="card col-4"><h2>Your balance</h2><div class="stat"><strong class="member-balance ${balances[myId]>=0?'pos':'neg'}">${money(balances[myId]||0,currentTrip.currency)}</strong><small>${(balances[myId]||0)>=0?'You should receive':'You owe'}</small></div></div><div class="card col-6"><h2>Expenses</h2><div class="list">${expenses.length?expenses.map(e=>`<div class="row"><span class="row-main"><strong>${esc(e.description)}</strong><span class="muted">Paid by ${esc(e.paid_by_name)} · ${esc(e.expense_date)}</span></span><span class="amount">${money(e.amount,currentTrip.currency)}</span></div>`).join(''):'<div class="empty">No expenses yet.</div>'}</div></div><div class="card col-6"><h2>Travelers</h2><div class="list">${members.map(m=>`<div class="row"><span class="row-main"><strong>${esc(m.display_name)}</strong><span class="muted">${m.joined_at?'Joined':'Invitation not used'}</span></span><span><span class="pill ${m.role==='ADMIN'?'admin':''}">${m.role}</span> <b class="member-balance ${(balances[m.id]||0)>=0?'pos':'neg'}">${money(balances[m.id]||0,currentTrip.currency)}</b></span></div>`).join('')}</div></div></section>`;
}
function calcBalances(){let b={};members.forEach(m=>b[m.id]=0);expenses.forEach(e=>{b[e.paid_by_member_id]=(b[e.paid_by_member_id]||0)+Number(e.amount);(e.shares||[]).forEach(s=>b[s.member_id]=(b[s.member_id]||0)-Number(s.share_amount))});return b}
async function startTrip(){if(!confirm('Start this trip? Expenses can then be added.'))return;let {error}=await sb.rpc('start_trip',{p_trip_id:currentTrip.id});if(error)return toast(error.message,true);await openTrip(currentTrip.id)}
function inviteModal(){modal('Add user and create QR',`<form id="inviteForm"><div class="field"><label>Traveler name</label><input name="display_name" maxlength="60" required placeholder="Swetha"></div><div class="actions"><button class="btn" id="inviteSubmitBtn">Create one-time QR</button></div></form><div id="qrResult"></div>`);document.getElementById('inviteForm').onsubmit=async e=>{e.preventDefault();let n=new FormData(e.target).get('display_name');let btn=document.getElementById('inviteSubmitBtn');btn.disabled=true;let {data,error}=await sb.rpc('create_invite',{p_trip_id:currentTrip.id,p_display_name:n});btn.disabled=false;if(error)return toast(error.message,true);let url=new URL(location.href);url.search='';url.searchParams.set('invite',data.token);let uid='qr'+data.member_id.replace(/-/g,'');document.getElementById('qrResult').insertAdjacentHTML('afterbegin',`<div class="qr-box" id="${uid}"><canvas id="${uid}c"></canvas></div><p class="muted center">One-time QR for <b>${esc(n)}</b></p><button class="btn secondary" id="${uid}copy">Copy join link</button>`);document.getElementById(uid+'copy').onclick=()=>navigator.clipboard.writeText(url.toString()).then(()=>toast('Join link copied'));e.target.reset();e.target.querySelector('input').focus();try{if(typeof QRCode==='undefined')throw new Error('QR library did not load');await QRCode.toCanvas(document.getElementById(uid+'c'),url.toString(),{width:280,margin:2})}catch(err){document.getElementById(uid).innerHTML=`<p class="warning">QR code unavailable (${esc(err.message)}). Use the copy link button below.</p>`}}}
function joinScreen(){root.innerHTML=`<section class="card center"><span class="eyebrow">Trip invitation</span><h1>Join the trip</h1><p class="muted">This QR invitation is single-use and is linked to the traveler name chosen by the admin.</p><button class="btn" onclick="acceptInvite()">Join now</button></section>`}
async function acceptInvite(){let {data,error}=await sb.rpc('accept_invite',{p_token:inviteToken});if(error)return toast(error.message,true);history.replaceState({},'',location.pathname);toast('You joined '+data.trip_name);await openTrip(data.trip_id)}
function expenseModal(){let active=members.filter(m=>m.joined_at);modal('Add expense',`<form id="expenseForm" class="form-grid"><div class="field full"><label>Description</label><input name="description" maxlength="120" required placeholder="Dinner"></div><div class="field"><label>Amount</label><input name="amount" type="number" min="0.01" step="0.01" required></div><div class="field"><label>Paid by</label><select name="paid_by_member_id">${active.map(m=>`<option value="${m.id}" ${m.id===currentTrip.member_id?'selected':''}>${esc(m.display_name)}</option>`).join('')}</select></div><div class="field"><label>Date</label><input name="expense_date" type="date" value="${new Date().toISOString().slice(0,10)}" required></div><div class="field full"><label>Split equally among</label><div class="check-grid">${active.map(m=>`<label class="check"><input type="checkbox" name="split" value="${m.id}" checked> ${esc(m.display_name)}</label>`).join('')}</div></div><div class="field full"><button class="btn">Save expense</button></div></form>`);document.getElementById('expenseForm').onsubmit=async e=>{e.preventDefault();let f=new FormData(e.target), split=f.getAll('split');if(!split.length)return toast('Select at least one traveler',true);let {error}=await sb.rpc('add_expense',{p_trip_id:currentTrip.id,p_description:f.get('description'),p_amount:Number(f.get('amount')),p_paid_by_member_id:f.get('paid_by_member_id'),p_expense_date:f.get('expense_date'),p_split_member_ids:split});if(error)return toast(error.message,true);closeModal();await openTrip(currentTrip.id)}}
async function endTrip(){if(!confirm('End this trip? An Excel file will download and ALL trip data will be permanently deleted.'))return;let {data,error}=await sb.rpc('end_trip_export_delete',{p_trip_id:currentTrip.id});if(error)return toast(error.message,true);exportWorkbook(data);toast('Trip exported and deleted');await home()}
function exportWorkbook(d){let wb=XLSX.utils.book_new();let summary=[{Trip:d.trip.name,Destination:d.trip.destination,Currency:d.trip.currency,Started:d.trip.started_at,Ended:d.ended_at,Total:d.expenses.reduce((s,e)=>s+Number(e.amount),0)}];XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(summary),'Trip Summary');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(d.members.map(m=>({Name:m.display_name,Role:m.role,Joined:m.joined_at||'Not joined'}))),'Members');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(d.expenses.map(e=>({Date:e.expense_date,Description:e.description,Amount:e.amount,PaidBy:e.paid_by_name,CreatedBy:e.created_by_name}))), 'Expenses');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(d.shares.map(s=>({Expense:s.expense_description,Member:s.member_name,Share:s.share_amount}))), 'Shares');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(d.settlements||[]),'Settlements');XLSX.writeFile(wb,`${d.trip.name.replace(/[^a-z0-9]/gi,'_')}_final.xlsx`)}
window.createTripModal=createTripModal;window.home=home;window.openTrip=openTrip;window.startTrip=startTrip;window.inviteModal=inviteModal;window.acceptInvite=acceptInvite;window.expenseModal=expenseModal;window.endTrip=endTrip;
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;document.getElementById('installBtn').classList.remove('hidden')});document.getElementById('installBtn').onclick=()=>deferredPrompt?.prompt();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');init();
