-- TripSplit clean install. WARNING: this deletes only TripSplit objects listed below.
create extension if not exists pgcrypto;

drop function if exists public.end_trip_export_delete(uuid) cascade;
drop function if exists public.add_expense(uuid,text,numeric,uuid,date,uuid[]) cascade;
drop function if exists public.accept_invite(text) cascade;
drop function if exists public.create_invite(uuid,text) cascade;
drop function if exists public.start_trip(uuid) cascade;
drop function if exists public.trip_dashboard(uuid) cascade;
drop function if exists public.my_trips() cascade;
drop function if exists public.create_trip(text,text,text,date,date,text) cascade;
drop function if exists public.is_trip_member(uuid) cascade;
drop function if exists public.is_trip_admin(uuid) cascade;
drop table if exists public.trip_expense_shares cascade;
drop table if exists public.trip_expenses cascade;
drop table if exists public.trip_invites cascade;
drop table if exists public.trip_members cascade;
drop table if exists public.trips cascade;

create table public.trips(id uuid primary key default gen_random_uuid(),name text not null check(length(name) between 1 and 80),destination text,currency text not null default 'INR',start_date date,end_date date,started_at timestamptz,created_by uuid not null references auth.users(id),created_at timestamptz not null default now());
create table public.trip_members(id uuid primary key default gen_random_uuid(),trip_id uuid not null references public.trips(id) on delete cascade,user_id uuid references auth.users(id),display_name text not null,role text not null check(role in('ADMIN','MEMBER')),joined_at timestamptz,created_at timestamptz not null default now(),unique(trip_id,user_id));
create table public.trip_invites(id uuid primary key default gen_random_uuid(),trip_id uuid not null references public.trips(id) on delete cascade,member_id uuid not null unique references public.trip_members(id) on delete cascade,token_hash text not null unique,expires_at timestamptz not null default(now()+interval '30 days'),used_at timestamptz,created_at timestamptz not null default now());
create table public.trip_expenses(id uuid primary key default gen_random_uuid(),trip_id uuid not null references public.trips(id) on delete cascade,description text not null,amount numeric(14,2) not null check(amount>0),paid_by_member_id uuid not null references public.trip_members(id),expense_date date not null,created_by_member_id uuid not null references public.trip_members(id),created_at timestamptz not null default now());
create table public.trip_expense_shares(id uuid primary key default gen_random_uuid(),expense_id uuid not null references public.trip_expenses(id) on delete cascade,member_id uuid not null references public.trip_members(id),share_amount numeric(14,2) not null check(share_amount>=0),unique(expense_id,member_id));

alter table public.trips enable row level security;alter table public.trip_members enable row level security;alter table public.trip_invites enable row level security;alter table public.trip_expenses enable row level security;alter table public.trip_expense_shares enable row level security;
-- No direct browser table access. All operations use security-definer RPCs with explicit membership checks.
revoke all on public.trips,public.trip_members,public.trip_invites,public.trip_expenses,public.trip_expense_shares from anon,authenticated;

create or replace function public.create_trip(name text,destination text,currency text,start_date date,end_date date,display_name text) returns uuid language plpgsql security definer set search_path=public as $$declare tid uuid;begin if auth.uid() is null then raise exception 'Not authenticated';end if;insert into trips(name,destination,currency,start_date,end_date,created_by) values(name,nullif(destination,''),currency,start_date,end_date,auth.uid()) returning id into tid;insert into trip_members(trip_id,user_id,display_name,role,joined_at) values(tid,auth.uid(),display_name,'ADMIN',now());return tid;end$$;
create or replace function public.my_trips() returns table(trip_id uuid,name text,destination text,currency text,role text) language sql security definer set search_path=public as $$select t.id,t.name,t.destination,t.currency,m.role from trips t join trip_members m on m.trip_id=t.id where m.user_id=auth.uid() order by t.created_at desc$$;
create or replace function public.trip_dashboard(p_trip_id uuid) returns jsonb language plpgsql security definer set search_path=public as $$declare me trip_members;out jsonb;begin select * into me from trip_members where trip_id=p_trip_id and user_id=auth.uid();if me.id is null then raise exception 'You are not a trip member';end if;select jsonb_build_object('trip',jsonb_build_object('id',t.id,'name',t.name,'destination',t.destination,'currency',t.currency,'start_date',t.start_date,'end_date',t.end_date,'started_at',t.started_at,'role',me.role,'member_id',me.id),'members',(select coalesce(jsonb_agg(jsonb_build_object('id',m.id,'display_name',m.display_name,'role',m.role,'joined_at',m.joined_at) order by m.created_at),'[]') from trip_members m where m.trip_id=t.id),'expenses',(select coalesce(jsonb_agg(jsonb_build_object('id',e.id,'description',e.description,'amount',e.amount,'expense_date',e.expense_date,'paid_by_member_id',e.paid_by_member_id,'paid_by_name',pm.display_name,'shares',(select coalesce(jsonb_agg(jsonb_build_object('member_id',s.member_id,'share_amount',s.share_amount)),'[]') from trip_expense_shares s where s.expense_id=e.id)) order by e.expense_date desc,e.created_at desc),'[]') from trip_expenses e join trip_members pm on pm.id=e.paid_by_member_id where e.trip_id=t.id)) into out from trips t where t.id=p_trip_id;return out;end$$;
create or replace function public.start_trip(p_trip_id uuid) returns void language plpgsql security definer set search_path=public as $$begin update trips set started_at=coalesce(started_at,now()) where id=p_trip_id and exists(select 1 from trip_members where trip_id=p_trip_id and user_id=auth.uid() and role='ADMIN');if not found then raise exception 'Admin access required';end if;end$$;
create or replace function public.create_invite(p_trip_id uuid,p_display_name text) returns jsonb language plpgsql security definer set search_path=public as $$declare mid uuid;raw text;begin if not exists(select 1 from trip_members where trip_id=p_trip_id and user_id=auth.uid() and role='ADMIN') then raise exception 'Admin access required';end if;insert into trip_members(trip_id,display_name,role) values(p_trip_id,p_display_name,'MEMBER') returning id into mid;raw:=encode(gen_random_bytes(24),'hex');insert into trip_invites(trip_id,member_id,token_hash) values(p_trip_id,mid,encode(digest(raw,'sha256'),'hex'));return jsonb_build_object('token',raw,'member_id',mid);end$$;
create or replace function public.accept_invite(p_token text) returns jsonb language plpgsql security definer set search_path=public as $$declare inv trip_invites;tn text;begin select * into inv from trip_invites where token_hash=encode(digest(p_token,'sha256'),'hex') for update;if inv.id is null or inv.used_at is not null or inv.expires_at<now() then raise exception 'Invitation is invalid, expired, or already used';end if;if exists(select 1 from trip_members where trip_id=inv.trip_id and user_id=auth.uid()) then raise exception 'This device is already joined to the trip';end if;update trip_members set user_id=auth.uid(),joined_at=now() where id=inv.member_id;update trip_invites set used_at=now() where id=inv.id;select name into tn from trips where id=inv.trip_id;return jsonb_build_object('trip_id',inv.trip_id,'trip_name',tn);end$$;
create or replace function public.add_expense(p_trip_id uuid,p_description text,p_amount numeric,p_paid_by_member_id uuid,p_expense_date date,p_split_member_ids uuid[]) returns uuid language plpgsql security definer set search_path=public as $$declare me uuid;eid uuid;n int;base numeric(14,2);remaining numeric(14,2);mid uuid;i int:=0;begin select id into me from trip_members where trip_id=p_trip_id and user_id=auth.uid() and joined_at is not null;if me is null then raise exception 'Member access required';end if;if not exists(select 1 from trips where id=p_trip_id and started_at is not null) then raise exception 'Admin must start the trip first';end if;if not exists(select 1 from trip_members where id=p_paid_by_member_id and trip_id=p_trip_id and joined_at is not null) then raise exception 'Invalid payer';end if;n:=coalesce(array_length(p_split_member_ids,1),0);if n=0 then raise exception 'Choose at least one member';end if;if exists(select 1 from unnest(p_split_member_ids) x where not exists(select 1 from trip_members where id=x and trip_id=p_trip_id and joined_at is not null)) then raise exception 'Invalid split member';end if;insert into trip_expenses(trip_id,description,amount,paid_by_member_id,expense_date,created_by_member_id) values(p_trip_id,p_description,p_amount,p_paid_by_member_id,p_expense_date,me) returning id into eid;base:=trunc((p_amount/n)::numeric,2);remaining:=p_amount-(base*n);foreach mid in array p_split_member_ids loop i:=i+1;insert into trip_expense_shares(expense_id,member_id,share_amount) values(eid,mid,base+case when i=1 then remaining else 0 end);end loop;return eid;end$$;
create or replace function public.end_trip_export_delete(p_trip_id uuid) returns jsonb language plpgsql security definer set search_path=public as $$declare out jsonb;begin if not exists(select 1 from trip_members where trip_id=p_trip_id and user_id=auth.uid() and role='ADMIN') then raise exception 'Admin access required';end if;select jsonb_build_object('trip',to_jsonb(t),'ended_at',now(),'members',(select coalesce(jsonb_agg(to_jsonb(m)),'[]') from trip_members m where m.trip_id=t.id),'expenses',(select coalesce(jsonb_agg(to_jsonb(e)||jsonb_build_object('paid_by_name',p.display_name,'created_by_name',c.display_name)),'[]') from trip_expenses e join trip_members p on p.id=e.paid_by_member_id join trip_members c on c.id=e.created_by_member_id where e.trip_id=t.id),'shares',(select coalesce(jsonb_agg(jsonb_build_object('expense_description',e.description,'member_name',m.display_name,'share_amount',s.share_amount)),'[]') from trip_expense_shares s join trip_expenses e on e.id=s.expense_id join trip_members m on m.id=s.member_id where e.trip_id=t.id),'settlements','[]'::jsonb) into out from trips t where t.id=p_trip_id;delete from trips where id=p_trip_id;return out;end$$;
grant execute on function public.create_trip(text,text,text,date,date,text),public.my_trips(),public.trip_dashboard(uuid),public.start_trip(uuid),public.create_invite(uuid,text),public.accept_invite(text),public.add_expense(uuid,text,numeric,uuid,date,uuid[]),public.end_trip_export_delete(uuid) to authenticated;
